# Introduction to Jupyter

### Keyboard shortcuts

- Pres Esc key to enable / disable
- Executing cells - Esc, Shft-Enter OR Ctrl-Enter
- Adding a cell above Esc, A
- Adding a cell below - Esc, B
- Delete a cell - Esc, D, D
- Copy, Cut, Paste - Ctrl-C, Ctrl-X, Ctrl-V
- Undo - Ctrl-Z
- Select all - Ctrl-A
- Comment Cell - Ctrl-/

# Machine Learning Overview

John fill in this outline with what you want to talk about

# Managing Packages
This is a review from the Data Analysis with Python Course

### PyPi
- PyPi is the index of publicly available packages
- https://pypi.org/

### Pip
- Check if pip is installed
    1. Open a command prompt (Windows) or terminal (Mac)
    2. Type 'python -V'
    3. Type 'pip -V'
- pip is the tool used for managing packages in Python
- Installed with python3
- Install all packages that are not a part of standard python library
- https://pypi.org/project/pip/

### Package we will use in this course
- numpy, matplotlib, pandas, sklearn
- Check what packages are installed with help("modules")
- Install packages from the command line
    1. Open a command prompt (Windows) or Terminal (Mac)
    2. Type 'pip install <package-name>' (ex. pip install pandas, pip install matplotlib)

### Importing packages
- use import statement to allow your code to use a package

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Python Packages for Data Science

- SciKit Learn - https://scikit-learn.org/stable/

# Ways to Importing Data

### From a Database

1. MySQL (mysql.connector)
2. SQL Server / Sybase (pymssql)
3. DB2 (ibm_db)
4. PostgreSQL (psycopg2)
5. MongoDB / Other NoSQL databases (pymongo)

### From a file into NumPy Array
import numpy as np
csv = np.genfromtxt ('file.csv', delimiter=",")

### From Scikit Learn
from sklearn.datasets import load_iris
iris = load_iris()

In [ ]:
# Load the dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
df = pd.read_csv(url, names=names)  

# Explore the Data

In [ ]:
# Explore the data
df.head()

In [ ]:
# What is the shape of the data?
df.shape

# Splitting Data into Training and Test Data

In [ ]:
# Split the dataset into its attributes and labels
x = dataset.iloc[:, :-1].values  
y = dataset.iloc[:, 4].values 
print(x, y)

In [36]:
# Split into training and test datasets
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

[5.  3.  1.6 0.2]


# Feature Scaling


In [38]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(x_train)

x_train = scaler.transform(x_train)  
x_test = scaler.transform(x_test) 

# Training and Predictions

In [41]:
# Train the data
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=5)  
classifier.fit(x_train, y_train)   

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [44]:
# Make predictions
y_pred = classifier.predict(x_test)
print(y_pred)

['Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa']


# Evaluating the Algorithm

### Common Metrics for Evalutaion
- confusion matrix
- precision
- recall
- f1 score

In [45]:
# 
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 

[[12  0  0]
 [ 0  8  2]
 [ 0  0  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      0.80      0.89        10
 Iris-virginica       0.80      1.00      0.89         8

      micro avg       0.93      0.93      0.93        30
      macro avg       0.93      0.93      0.93        30
   weighted avg       0.95      0.93      0.93        30



# Plotting and Visualization

In [ ]:
# TODO

# Export Your Script

File -> Download As -> Python (.py)

# Next Steps

Take our next course!